### ISSUE TITLE
Websocket API

### ISSUE THREAD

**Issue by RZ781** [sanand0/minecraft-websocket#2]
Can you provide a link to the documentation for the Minecraft Websocket API? I am struggling to find it online, and have heard people say that it is not available. If that is the case, can you provide the link to where you got the limited information?

**Comment by sanand0** [comment]
@RZ781 the API isn't documented, I'm afraid. I've added links to the references in the tutorial: https://github.com/sanand0/minecraft-websocket/tree/master/tutorial#subscribe-to-chat-messages
